### ISSUE TITLE
Insert Higlighting in ATOM

### ISSUE THREAD

**Issue by rondijkstra** [diesire/atom-language-abap#10]
Hi,
Well it's not really a bug or so; but I have downloaded the ABAP Highlighting into Atom, but how can I activate it in Atom so it displays the ABAP highlighting correctly?
Many thanks!
Ron.

**Comment by larshp** [comment]
Restart ATOM after installing the package(I'm not sure if this is required)

and then the highlighting should be activated for files named `*.abap`

**Comment by rondijkstra** [comment]
Rgr..! I also found out I could apply formatting to choose ABAP from lower right 'system tray' (within ATOM).

**Comment by rondijkstra** [comment]
hmm I noticed the pretty-printer / auto indent doesn't work on unformatted texts?
